/**
 * Implementation of method calls defined in `service.yml` files
 * This file is generated by the rest-tool tool.
 */
var services = require('rest-tool-common').services;

var server = require('./server.js');

//=============================================================================
// Put your mock method implementations here
