/**
 * Implementation of method calls defined in `service.yml` files
 * This file is generated by the restapi tool.
 * To change the first part of this file, you should modify the template used by the tool.
 * The template can be found here: <project-root>/templates/server/api.js.mustache
 */
var services = require('rest-tool-common').services;

var server = require('./server.js');

//=============================================================================
// BEGIN mock method implementations
// The functions below are generated from the corresponding service descriptors
// The name is defined by the `implementation` property and the content file is defined
// by the mockBody property. The `get`, `put`, etc. prefix is defined by the method name.

// END mock method implementations
//=============================================================================
